### PR TITLE
Change the theme of Stardust terrain

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR changes the theme of the _Stardust_ terrain.

- Music AI: _Udio_
- Music prompt: `Mysterious, Fantasy, Instrumental, 160 bpm, Cinematic classical`
- Soundscape AI: _Tango 2_
- Soundscape prompt: `Long continous ringing`

[Here](https://github.com/user-attachments/assets/36d192f7-4db2-4cea-98c1-4bd46f2dfbbb) is a version of the theme without the soundscape.

### CODE REVIEW

**Comment by madaosoul** [comment]
The soundscape version sounds terrible. I advise against using that. There are royalty free sound effects of chimes or other ambients that evoke magical atmosphere that should sound better, e.g. https://pixabay.com/sound-effects/windchimes-96khz-20140/

**Comment by Fabrice-TIERCELIN** [comment]
OK, I will look at it. `wind chimes` are good keywords. Have you got others like this?

**Comment by madaosoul** [comment]
"Magic", "fairy" and "ambience" come to mind. Would be good if you combined a couple of them, and maybe added bird sounds. Here are some more examples I found:
https://pixabay.com/sound-effects/magic-sparkle-190030/
https://pixabay.com/sound-effects/little-secrets-fairy-tale-sound-8395/
https://pixabay.com/sound-effects/fairy-sound-6469/
https://pixabay.com/sound-effects/night-ambience-17064/
https://pixabay.com/sound-effects/birds-19624/

**Comment by Fabrice-TIERCELIN** [comment]
I have remade the soundscape. It's a _drone music_ used as soundscape.

- Soundscape AI: _Udio_
- Soundscape prompt: `choir, calm, serenity, soundscape, drone music, monotone`

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, I think you have missed this notification

**Pull request merged**
